---
# Task erstellt config-build, pusht die config auf das device und fuehrt
# einen commit durch. Standardmaessig werden einzelne Hierarchie-Ebenen
# der Junos-config ersetzt (Parameter load: 'update').

- name: PUSH & COMMIT (CHECK)
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:
    - block:

      - name: Push config to device...
        juniper_junos_config:
          src: '{{ junos_conf }}'
          load: 'update'
          timeout: '60'
          # commit vs compare bei ausfuehrung per extra variable (-e) angeben:
          # ansible-playbook main.yml -e commit=yes|no
          commit: '{{ commit }}'
          # confirm optional per extra variable angeben:
          # ansible-playbook main.yml -e 'commit=yes confirm=2'
          confirm: "{{ confirm if confirm is defined else omit }}"
          diffs_file: '{{ compare_conf }}'
        register: response

      - name: 'Output diff if changes are present, else skip:'
        debug:
          var: response.diff_lines
        when: response.diff_lines is defined

      - name: 'Message from juniper_junos_config:'
        debug:
          var: response.msg

      when: push is not defined