---
- name: GENERATE JUNOS CONFIGURATION (Juniper EX extern access)
  hosts: ext_ex_access
  connection: local
  gather_facts: no

  # Ansible schaut in roles/<role name>/tasks/main.yaml und fuehrt die
  # dortigen Tasks aus.
  # Der Task 'template' in der jeweiligen main.yml fuellt das Jinja2-
  # Template der jeweiligen Role mit den Variablen aus host_vars und
  # group_vars und generiert daraus die Junos config.
  roles:
    - ext_ex_access