# Task erstellt config-build, pusht die config auf das device und fuehrt 
# einen commit durch. Standardmaessig werden einzelne Hierarchie-Ebenen 
# der Junos-config ersetzt (Parameter load: 'update').

- name: ASSEMBLE, PUSH & COMMIT
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:

    - name: Assemble configuration parts
      local_action: assemble src={{ build_dir }} dest={{ junos_conf }}

    - name: Push config to device and commit...
      juniper_junos_config:
        src: "{{ junos_conf }}"
        load: 'update'
        timeout: '60'
#       confirm: 3
      register: response

    - name: 'Output diff if changes are present, else skip:'
      debug:
        var: response.diff_lines
      when: response.diff_lines is defined

    - name: 'Message from juniper_junos_config:'
      debug:
        var: response.msg
    