# Task erstellt einen config-build, fuehrt aber anstelle eines commits ein
# commit check und anschließenden diff durch

- name: ASSEMBLE, PUSH & COMPARE
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:

    - name: Assemble configuration parts
      local_action: assemble src={{ build_dir }} dest={{ junos_conf }}

    - name: Push config to device, commit check and compare...
      juniper_junos_config:
        src: '{{ junos_conf }}'
        load: 'update'
        commit: 'no'
        check: 'yes'
        diff: 'yes'
        diffs_file: '{{ compare_conf }}'
      register: response

    - name: 'Output diff if changes are present, else skip:'
      debug:
        var: response.diff_lines
      when: response.diff_lines is defined

    - name: 'Message from juniper_junos_config:'
      debug:
        var: response.msg