---
- name: GENERATE JUNOS CONFIGURATION (Juniper EX intern core)
  hosts: int_ex_core
  connection: local
  gather_facts: no

  # Ansible schaut in roles/<role name>/tasks/main.yaml und fuehrt die
  # dortigen Tasks aus.
  # Der Task 'template' in der jeweiligen main.yml fuellt das Jinja2-
  # Template der jeweiligen Role mit den Variablen aus host_vars und
  # group_vars und generiert daraus die Junos config.
  roles:
    - int_ex_core