# Task erstellt config-build, pusht die config auf das device und fuehrt 
# einen commit durch. Standardmaessig werden einzelne Hierarchie-Ebenen 
# der Junos-config ersetzt (Parameter load: 'update').

- name: Build + Push configuration
  hosts: all
  roles:
    - Juniper.junos

  tasks:

    - name: Push config to device and commit
      juniper_junos_config:
        src: "{{ junos_conf }}"
        load: 'update'
        timeout: '60'
#       confirm: 3
      register: response
    - name: junos_config output...
      debug:
        var: response

