FROM python:3.7-slim

LABEL Name="exampleorg NOC Ansible-Juniper Docker Image fuer Jenkins Pipeline"

ARG keypath_credstore
ARG user

ARG workdir=ansible-juniper
ARG keyfile=/home/$user/.ssh/id_rsa

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y vim openssh-client iputils-ping dnsutils

RUN mkdir -p /$workdir
ADD . /$workdir
WORKDIR /$workdir

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN ansible-galaxy install -r requirements.yml

RUN useradd --create-home --shell /bin/bash $user
COPY keyfile $keyfile
RUN chown -R $user:$user /$workdir $keyfile
RUN chmod 600 $keyfile

USER $user
