#! /bin/bash
conf_yml=kami-kaze.yml
junos_applications=junos_applications

rm -f ${conf_yml}


cat set_conf.txt | grep "security zones" | awk '{print $5}' | uniq > zones.tmp
#cat zones.tmp 
i=`cat zones.tmp | wc -l`
head=1
echo "zones:" >> ${conf_yml}
#firewallzones
    while [ ${i} -ge ${head} ]; do

        zone=`cat zones.tmp | head -${head} | tail -1 `
        cat set_conf.txt | grep -E "(^| )${zone}( |$)" | grep "address-book address" | grep -v "address-set" | grep -v deactivate | awk '{print $8}' > addr-name.tmp
        cat set_conf.txt | grep -E "(^| )${zone}( |$)" | grep "address-book address" | grep -v "address-set" | grep -v deactivate | awk '{print $9}' > addr-ip.tmp
        head=`expr $head + 1`
        #output
        echo "  $zone:" >> ${conf_yml}
        iaddr=`cat addr-name.tmp | wc -l`
        headaddr=1
        echo "    addresses:" >> ${conf_yml}
        while [ ${iaddr} -ge ${headaddr} ]; do
        addrname=`cat addr-name.tmp | head -${headaddr} | tail -1`
        addrip=`cat addr-ip.tmp | head -${headaddr} | tail -1`
        #output
        echo "      ${addrname}: ${addrip}" >> ${conf_yml}
        headaddr=`expr ${headaddr} + 1`
   done
        #address-sets
        cat set_conf.txt | grep -E "(^| )${zone}( |$)" | grep "address-set" | grep -v deactivate | awk '{print $8}' | uniq > addr-set.tmp
        iset=`cat addr-set.tmp | wc -l`
        headset=1
        echo "    addrsets:" >> ${conf_yml}   
        while [ ${iset} -ge ${headset} ]; do
            addrset=`cat addr-set.tmp | head -${headset} | tail -1`
            #output
            echo -n "      ${addrset}: [">> ${conf_yml}
            cat set_conf.txt | grep -E "(^| )${zone}( |$)" | grep "address-set" | grep -v deactivate | grep -E "(^| )${addrset}( |$)" | awk '{print $10}' > addr-set-names.tmp
            isetnames=`cat addr-set-names.tmp | wc -l`
            headsetnames=1
            while [ ${isetnames} -ge ${headsetnames} ]; do
        addrsetname=`cat addr-set-names.tmp | head -${headsetnames} | tail -1`
        
            if [ ${headsetnames} -lt ${isetnames} ]; then
            echo -n "${addrsetname}," >> ${conf_yml}
            fi
            if [ ${headsetnames} -eq ${isetnames} ]; then
            echo "${addrsetname}]" >> ${conf_yml}
            fi
        headsetnames=`expr ${headsetnames} + 1`
        done
    headset=`expr ${headset} + 1`    
    done     

done

#default-applications

cat ${junos_applications} | grep -v application-set | awk '{print $6}' | uniq > default-applications.tmp
idefault=`cat default-applications.tmp | wc -l`
headdefault=1
echo "default-applications:" >> ${conf_yml}
    while [ ${idefault} -ge ${headdefault} ]; do
         default=`cat default-applications.tmp | head -${headdefault} | tail -1`       
         headdefault=`expr ${headdefault} + 1 `
         echo "  ${default}:" >> ${conf_yml}
      


    #default-alg
        cat junos_applications | grep -E "(^| )${default}( |$)" | grep alg | awk -Falg '{print $2}' | awk '{print $1}' > defaultalg.tmp
        idefaultalg=`cat defaultalg.tmp | wc -l`
        if [ ${idefaultalg} -gt 0 ];then
                if [ ${idefaultalg} -eq 1 ];then
                    defaultalg=`cat defaultalg.tmp`
                    echo "    alg: ${defaultalg}" >> ${conf_yml}
                fi
                if [ ${idefaultalg} -gt 1 ];then
                echo -n "    alg: [" >> ${conf_yml}
                headdefaultalg=1
                        while [ ${idefaultalg} -ge ${headdefaultalg} ]; do
                            defaultalg=`cat defaultalg.tmp | head -${headdefaultalg} | tail -1`

                            if [ ${headdefaultalg} -lt ${idefaultalg} ]; then
                            echo -n "${defaultalg}," >> ${conf_yml}
                            fi
                            if [ ${headdefaultalg} -eq ${idefaultalg} ]; then
                            echo "${defaultalg}]" >> ${conf_yml}
                            fi
                        headdefaultalg=`expr ${headdefaultalg} + 1`
                        done
                fi
        fi


    #default-protocol
        cat junos_applications | grep -E "(^| )${default}( |$)" | grep protocol | awk -Fprotocol '{print $2}' | awk '{print $1}' > defaultprotocol.tmp
        idefaultprotocol=`cat defaultprotocol.tmp | wc -l`
        if [ ${idefaultprotocol} -gt 0 ];then
                if [ ${idefaultprotocol} -eq 1 ];then
                    defaultprotocol=`cat defaultprotocol.tmp`
                    echo "    protocol: ${defaultprotocol}" >> ${conf_yml}
                fi
                if [ ${idefaultprotocol} -gt 1 ];then
                echo -n "    protocol: [" >> ${conf_yml}
                headdefaultprotocol=1
                        while [ ${idefaultprotocol} -ge ${headdefaultprotocol} ]; do
                            defaultprotocol=`cat defaultprotocol.tmp | head -${headdefaultprotocol} | tail -1`

                            if [ ${headdefaultprotocol} -lt ${idefaultprotocol} ]; then
                            echo -n "${defaultprotocol}," >> ${conf_yml}
                            fi
                            if [ ${headdefaultprotocol} -eq ${idefaultprotocol} ]; then
                            echo "${defaultprotocol}]" >> ${conf_yml}
                            fi
                        headdefaultprotocol=`expr ${headdefaultprotocol} + 1`
                        done
                fi
        fi


         
    #default-source
        cat junos_applications | grep -E "(^| )${default}( |$)" | grep source-port | awk -Fsource-port '{print $2}' | awk '{print $1}' > defaultsource.tmp
		idefaultsource=`cat defaultsource.tmp | wc -l`
		if [ ${idefaultsource} -gt 0 ];then
				if [ ${idefaultsource} -eq 1 ];then
					defaultsource=`cat defaultsource.tmp`
					echo "    source-port: ${defaultsource}" >> ${conf_yml}
				fi
				if [ ${idefaultsource} -gt 1 ];then
				echo -n "    source-port: [" >> ${conf_yml}
				headdefaultsource=1
						while [ ${idefaultsource} -ge ${headdefaultsource} ]; do
							defaultsource=`cat defaultsource.tmp | head -${headdefaultsource} | tail -1`

							if [ ${headdefaultsource} -lt ${idefaultsource} ]; then
							echo -n "${defaultsource}," >> ${conf_yml}
							fi
							if [ ${headdefaultsource} -eq ${idefaultsource} ]; then
							echo "${defaultsource}]" >> ${conf_yml}
							fi
						headdefaultsource=`expr ${headdefaultsource} + 1`
						done
				fi
		fi     
         
         
    #default-destination
        cat junos_applications | grep -E "(^| )${default}( |$)" | grep destination-port | awk -Fdestination-port '{print $2}' | awk '{print $1}' > defaultdestination.tmp
		idefaultdestination=`cat defaultdestination.tmp | wc -l`
		if [ ${idefaultdestination} -gt 0 ];then
				if [ ${idefaultdestination} -eq 1 ];then
					defaultdestination=`cat defaultdestination.tmp`
					echo "    destination-port: ${defaultdestination}" >> ${conf_yml}
				fi
				if [ ${idefaultdestination} -gt 1 ];then
				echo -n "    destination-port: [" >> ${conf_yml}
				headdefaultdestination=1
						while [ ${idefaultdestination} -ge ${headdefaultdestination} ]; do
							defaultdestination=`cat defaultdestination.tmp | head -${headdefaultdestination} | tail -1`

							if [ ${headdefaultdestination} -lt ${idefaultdestination} ]; then
							echo -n "${defaultdestination}," >> ${conf_yml}
							fi
							if [ ${headdefaultdestination} -eq ${idefaultdestination} ]; then
							echo "${defaultdestination}]" >> ${conf_yml}
							fi
						headdefaultdestination=`expr ${headdefaultdestination} + 1`
						done
				fi
		fi         
            
    done
    
#defauls-application-sets

cat ${junos_applications} | grep application-set | awk '{print $6}' | uniq > defaultappsets.tmp
idefaultappset=`cat defaultappsets.tmp | wc -l`
headdefaultappset=1
echo "default-applicationsets:" >> ${conf_yml}
    while [ ${idefaultappset} -ge ${headdefaultappset} ]; do
    defaultappset=`cat defaultappsets.tmp | head -${headdefaultappset} | tail -1`
    #output
    echo -n "  ${defaultappset}: [" >> ${conf_yml}
    cat ${junos_applications} | grep application-set | grep -E "(^| )${defaultappset}( |$)" | awk '{print $8}' > defaultappsetdefaultapps.tmp
    idefaultappnames=`cat defaultappsetdefaultapps.tmp | wc -l`
    headsetdefaultapps=1
        while [ ${idefaultappnames} -ge ${headsetdefaultapps} ]; do
        defaultappsetname=`cat defaultappsetdefaultapps.tmp | head -${headsetdefaultapps} | tail -1`

            if [ ${headsetdefaultapps} -lt ${idefaultappnames} ]; then
            echo -n "${defaultappsetname}," >> ${conf_yml}
            fi
            if [ ${headsetdefaultapps} -eq ${idefaultappnames} ]; then
            echo "${defaultappsetname}]" >> ${conf_yml}
            fi
        headsetdefaultapps=`expr ${headsetdefaultapps} + 1`
        done
    headdefaultappset=`expr ${headdefaultappset} + 1`
    done


#applications

cat set_conf.txt | grep applications | grep -v application-set | awk '{print $4}' | uniq >  applications.tmp
iapp=`cat applications.tmp | wc -l`
echo "applications:" >> ${conf_yml}
headapp=1
    while [ ${iapp} -ge ${headapp} ]; do
    application=`cat applications.tmp | head -${headapp} | tail -1` 
    port=`cat set_conf.txt | grep applications | grep -v application-set | grep -E "(^| )${application}( |$)" | grep port | awk '{print $6}'`
    protocol=`cat set_conf.txt | grep applications | grep -v application-set | grep -E "(^| )${application}( |$)" | grep protocol | awk '{print $6}'`
    echo "  ${application}:" >> ${conf_yml}
    echo "    protocol: ${protocol}" >> ${conf_yml}
    echo "    port: ${port}" >> ${conf_yml}
    headapp=`expr ${headapp} + 1`
    done

cat set_conf.txt | grep application-set | awk '{print $4}' | uniq > appsets.tmp
iappset=`cat appsets.tmp | wc -l`
headappset=1
echo "applicationsets:" >> ${conf_yml}
    while [ ${iappset} -ge ${headappset} ]; do
    appset=`cat appsets.tmp | head -${headappset} | tail -1`
    #output
    echo -n "  ${appset}: [" >> ${conf_yml}
    cat set_conf.txt | grep application-set | grep ${appset} | awk '{print $6}' > appsetapps.tmp
    iappnames=`cat appsetapps.tmp | wc -l`
    headsetapps=1
        while [ ${iappnames} -ge ${headsetapps} ]; do
        appsetname=`cat appsetapps.tmp | head -${headsetapps} | tail -1`

            if [ ${headsetapps} -lt ${iappnames} ]; then
            echo -n "${appsetname}," >> ${conf_yml}
            fi
            if [ ${headsetapps} -eq ${iappnames} ]; then
            echo "${appsetname}]" >> ${conf_yml}
            fi
        headsetapps=`expr ${headsetapps} + 1`
        done
    headappset=`expr ${headappset} + 1`
    done


#firewall-policies

cat set_conf.txt | grep "security policies" | grep -v groups | grep -v traceoptions | grep -v "from-zone untrust to-zone ServerLAN" | grep -v internet-access-office | grep -v default-deny | grep -v chef-to-all | awk '{print $5,$6,$7,$8,$9}' | uniq > policies.tmp
ipolicies=`cat policies.tmp | wc -l`
headpolicies=1
echo "policies:" >> ${conf_yml}
    while [ ${ipolicies} -ge ${headpolicies} ]; do
        policy=`cat policies.tmp | head -${headpolicies} | tail -1`
        fromzone=`echo ${policy} | awk '{print $1}'`
        tozone=`echo ${policy} | awk '{print $3}'`
        #policy-name
        policyname=`echo ${policy} | awk '{print $5}'`
        echo "${policyname}" >> policyname.tmp
        testname=`cat policyname.tmp | grep -E "(^| )${policyname}( |$)" | wc -l`
            if [ ${testname} -gt 1 ];then
                policyname=`echo ${policyname}${testname}`
                echo ${policyname} >> testname.tmp
            fi    
        echo "  ${policyname}:" >> ${conf_yml}
        echo "    fromzone: ${fromzone}" >> ${conf_yml}
        echo "    tozone: ${tozone}" >> ${conf_yml}
        # source-address
        cat set_conf.txt | grep "security policies" | grep "${policy}" | grep source-address | awk '{print $12}' > source.tmp
        isource=`cat source.tmp | wc -l`
            if [ ${isource} -eq 1 ];then
                source=`cat source.tmp`
                echo "    source: ${source}" >> ${conf_yml}
            fi
            if [ ${isource} -gt 1 ];then
               echo -n "    source: [" >> ${conf_yml}
               headsource=1
                    while [ ${isource} -ge ${headsource} ]; do
                        source=`cat source.tmp | head -${headsource} | tail -1`

                        if [ ${headsource} -lt ${isource} ]; then
                        echo -n "${source}," >> ${conf_yml}
                        fi
                        if [ ${headsource} -eq ${isource} ]; then
                        echo "${source}]" >> ${conf_yml}
                        fi
                    headsource=`expr ${headsource} + 1`
                    done 
            fi    
         # destination-address
        cat set_conf.txt | grep "security policies" | grep "${policy}" | grep destination-address | awk '{print $12}' > destination.tmp
        idestination=`cat destination.tmp | wc -l`
            if [ ${idestination} -eq 1 ];then
                destination=`cat destination.tmp`
                echo "    destination: ${destination}">> ${conf_yml}
            fi
            if [ ${idestination} -gt 1 ];then
               echo -n "    destination: [" >> ${conf_yml}
               headdestination=1
                    while [ ${idestination} -ge ${headdestination} ]; do
                        destination=`cat destination.tmp | head -${headdestination} | tail -1`

                        if [ ${headdestination} -lt ${idestination} ]; then
                        echo -n "${destination}," >> ${conf_yml}
                        fi
                        if [ ${headdestination} -eq ${idestination} ]; then
                        echo "${destination}]" >> ${conf_yml}
                        fi
                    headdestination=`expr ${headdestination} + 1`
                    done
            fi
         # application
        cat set_conf.txt | grep "security policies" | grep "${policy}" | grep application | awk '{print $12}' > application.tmp
        iapplication=`cat application.tmp | wc -l`
            if [ ${iapplication} -eq 1 ];then
                application=`cat application.tmp`
                echo "    application: ${application}" >> ${conf_yml}
            fi
            if [ ${iapplication} -gt 1 ];then
               echo -n "    application: [" >> ${conf_yml}
               headapplication=1
                    while [ ${iapplication} -ge ${headapplication} ]; do
                        application=`cat application.tmp | head -${headapplication} | tail -1`

                        if [ ${headapplication} -lt ${iapplication} ]; then
                        echo -n "${application}," >> ${conf_yml}
                        fi
                        if [ ${headapplication} -eq ${iapplication} ]; then
                        echo "${application}]" >> ${conf_yml}
                        fi
                    headapplication=`expr ${headapplication} + 1`
                    done
            fi 
                # action
        cat set_conf.txt | grep "security policies" | grep "${policy}" | grep then | awk '{print $11}' > action.tmp
        iaction=`cat action.tmp | wc -l`
            if [ ${iaction} -eq 1 ];then
                action=`cat action.tmp`
                echo "    action: ${action}" >> ${conf_yml}
            fi
            if [ ${iaction} -gt 1 ];then
               echo -n "    action: [" >> ${conf_yml}
               headaction=1
                    while [ ${iaction} -ge ${headaction} ]; do
                        action=`cat action.tmp | head -${headaction} | tail -1`

                        if [ ${headaction} -lt ${iaction} ]; then
                        echo -n "${action}," >> ${conf_yml}
                        fi
                        if [ ${headaction} -eq ${iaction} ]; then
                        echo "${action}]" >> ${conf_yml}
                        fi
                    headaction=`expr ${headaction} + 1`
                    done
            fi      
        headpolicies=`expr ${headpolicies} + 1`
    done
    
rm -f policyname.tmp
rm -f testname.tmp
rm -f *.tmp




#cat set_conf.txt | grep ${zone} | grep "address-book address" | grep -v "address-set" | grep set | awk '{print $8}' > addr-name.tmp
#cat set_conf.txt | grep ${zone} | grep "address-book address" | grep -v "address-set" | grep set | awk '{print $9}' > addr-ip.tmp


