---
- name: Get Device Interfaces Terse
  hosts: all
  vars:
    - ansible_connection: network_cli
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:

    - name: Retrieve interface status
      juniper_junos_command:
        commands:
          - "show interfaces terse"
      register: response

    - name: show interfaces terse
      debug:
        msg: "{{ response.stdout_lines }}"