---
- name: Get Device Facts
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:

    - name: Checking NETCONF connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 5

    - name: Retrieve Junos Version via junos_facts Modul
      junos_facts:
        provider: "{{ netconf_core }}"
      register: junosfacts

    - name: Retrieve Junos Version via juniper_junos_command Module
      juniper_junos_command:
        provider: "{{ netconf_juniper }}"
        commands:
          - "show version"
      register: juniperjunoscommand

    - name: junos_facts Output...
      debug: var=junosfacts['ansible_facts']['ansible_net_version']
    
    - name: juniper_junos_command Output...
      debug: var=juniperjunoscommand
