---
- name: Get Device Facts
  hosts: all
  roles:
    - Juniper.junos

  tasks:

    - name: Checking NETCONF connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 5

    - name: Retrieve Junos version via junos_facts module
      junos_facts:
      register: junosfacts
    - name: junos_facts Output...
      debug:
        msg: "Junos version: {{ ansible_net_version }}"
    
    - name: Retrieve Junos version via juniper_junos_command module
      juniper_junos_command:
        commands:
          - "show version"
      register: juniperjunoscommand
    - name: juniper_junos_command Output...
      debug: 
        var: juniperjunoscommand.stdout_lines[5]

    - name: Retrieve Junos version via juniper_junos_rpc module
      juniper_junos_rpc:
        rpcs:
          - "get-software-information"
      register: juniperjunosrpc
    - name: juniper_junos_rpc Output...
      debug:
        var: juniperjunosrpc
        #msg: "{{ juniperjunosrpc['parsed_output']['multi-routing-engine-results']['multi-routing-engine-item']['software-information']['junos-version'] }}"
