---
- name: Get Device Facts
  hosts: all
# connection: netconf
  roles:
    - Juniper.junos

  tasks:

    - name: Checking NETCONF connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 5

    - name: Retrieve Junos version via junos_facts module
      junos_facts:
      register: junosfacts
    - name: junos_facts Output...
      debug: var=junosfacts['ansible_facts']['ansible_net_version']
    
    - name: Retrieve Junos version via juniper_junos_command module
      juniper_junos_command:
        commands:
          - "show version"
      register: juniperjunoscommand
    - name: juniper_junos_command Output...
      debug: var=juniperjunoscommand

    - name: Retrieve Junos version via juniper_junos_rpc module
      juniper_junos_rpc:
        rpcs:
          - "get-software-information"
#       return_output: false
      register: juniperjunosrpc
    - name: juniper_junos_rpc Output...
      debug: var=juniperjunosrpc
