---
- name: Get neighbor information via LLDP
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:

    - name: Retrieve LLDP neighbor table
      junos_get_table:
        table: "LLDPNeighborTable"
        file: "lldp.yml" 
        host: "{{ inventory_hostname }}" 
      register: neighbors

    - name: Print lldp table
      debug:
        var: neighbors['resource']
        
    - name: Retrieve LLDP remote interfaces
      juniper_junos_command:
        commands:
          - "show lldp neighbors interface {{ item['local_int'] }}"
        format: xml
      with_items: "{{ neighbors['resource'] }}"
      register: show_lldp_if

    - name: Print lldp interfaces
      debug:
        msg: "{{ item.parsed_output['lldp-neighbors-information']['lldp-neighbor-information']['lldp-remote-port-id'] }}"
      with_items: "{{ show_lldp_if.results }}"

#   - name: Set interface descriptions
#     juniper_junos_config:
#       lines:
#         - set interfaces {{ item['local_int'] }} description "{{ item['remote_sysname'] }}"
#       load: 'merge'
#       commit: 'no'
#       check: 'yes'
#       diff: 'yes'
#     with_items: "{{ neighbors['resource'] }}"