---
- name: 'Collect Snapshot of LLDP Neighbors (Pre Configuration)'
  juniper_junos_jsnapy:
    action: 'snap_pre'
    test_files: 'tests/test_lldp_neighbors.yml'
  when: _action == 'snap_pre'
  tags: snap-pre

- name: 'Collect Snapshot of LLDP Neighbors (Post Configuration)'
  juniper_junos_jsnapy:
    action: 'snap_post'
    test_files: 'tests/test_lldp_neighbors.yml'
  when: _action == 'snap_post'
  tags: snap-post

- block:

  - name: 'Compare LLDP Neighbors Pre and Post Snapshots'
    juniper_junos_jsnapy:
      action: 'check'
      test_files: 'tests/test_lldp_neighbors.yml'
    register: test_lldp_neighbors

  - name: 'Verify all JSNAPy tests passed'
    assert:
      that:
        - 'test_lldp_neighbors.final_result == "Passed"'
        - 'test_lldp_neighbors.passPercentage == 100'

  # - name: Print the full test response
  #   debug:
  #     var: test_lldp_neighbors

  when: _action == 'check'
  tags: snap-check
