---
- name: 'Collect Snapshot of Interface Status (Pre Configuration)'
  juniper_junos_jsnapy:
    action: 'snap_pre'
    test_files: 'tests/test_interface_status.yml'
  when: _action == 'snap_pre'
  tags: snap-pre

- name: 'Collect Snapshot of Interface Status (Post Configuration)'
  juniper_junos_jsnapy:
    action: 'snap_post'
    test_files: 'tests/test_interface_status.yml'
  when: _action == 'snap_post'
  tags: snap-post

- block:

  - name: 'Compare Interface Status Pre and Post Snapshots'
    juniper_junos_jsnapy:
      action: 'check'
      test_files: 'tests/test_interface_status.yml'
    register: test_interface_status

  - name: 'Verify all JSNAPy tests passed'
    assert:
      that:
        - 'test_interface_status.final_result == "Passed"'
        - 'test_interface_status.passPercentage == 100'

  # - name: Print the full test response
  #   debug:
  #     var: test_interface_status

  when: _action == 'check'
  tags: snap-check
