---
- name: 'Create local build directories for configuration files'
  local_action: file path={{ build_dir }} state=directory

- name: 'Generate Junos configuration'
  local_action: template src=main.conf.j2 dest={{ junos_conf }}
