---
- name: Import cleanup playbook
  import_playbook: create-build-dirs.yml

- name: Get commited configuration of devices
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:

    - name: Retrieve config + save at ~/ansible_tmp/{hostname}/
      juniper_junos_config:
        retrieve: "committed"
        # format optional bei ausfuehrung per extra variable (-e) angeben:
        # ansible-playbook get-config.yml -e format=text|set|xml|json (default=text)
        format: "{{ format if format is defined else omit }}"
        dest_dir: "{{ base_dir }}"
      register: response